#!/bin/sh
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(js|cjs|mjs|json|md|yml|yaml|html|css)$' || true)
if [ -n "$files" ]; then
  pnpm prettier --write $files
  git add $files
fi
pnpm lint && pnpm check && pnpm test